### PR TITLE
Tweak German Translations

### PR DESCRIPTION
**Pull request by ghost**
Fixed translation inconsistency, and a better translation for Witch-Hazel and Skyris

### CODE REVIEW

**Comment by JT122406** [comment]
Are these already in BWG or will that need adjustments as well?

**Comment by JT122406** [comment]
nvm

**Comment by JT122406** [comment]
https://github.com/Potion-Studios/Oh-The-Biomes-Weve-Gone/pull/175

**Comment by ghost** [comment]
All done, I've also translated "Skyris" as "Himmelsbaum" now (means Sky tree), which I've also changed in the BWG lang file

**Review by JT122406 — APPROVED** [review]

**Pull request merged**
